### Notebook 01: Documentação e leitura de dados

Decidi começar pelo começo: documentação.

Em análise de dados, não basta você entender o que os números e códigos dizem: é preciso que os outros entendam. E por "os outros", me refiro a nossos chefes, colegas de redação, leitores, ou mesmo outros que, assim como nós dois, estamos estudando análise de dados, Pandas e afins.

Documentar significa registrar tudo o que você faz. Todos os passos que levam ao resultado final. Todo o trabalho, desde os dados brutos até a conclusão. O nome disso é transparência.

Você pode fazer isso usando # no meio dos códigos do notebook:

In [ ]:
# Assim, desta forma, pois o Python ignora tudo que vem depois deste símbolo.
# Eu posso até desenhar uma rosa, se eu quiser.
# ──────────────▒███░───░████████▒ 
# ───────────█████▒░█████░▒▒▒▒▒▒█████ 
# ──────────██▒▒▒▒██████████████▒▒▒██░ 
# ─────────██▒▒▒▒███▒██▒██▒▒█████▒░▒██ 
# ─────────█░▒▒▒██▒████████████▒█▒▒▒█░ 
# ─────────█▒▒▒▒██▒▒▒░▓▓▒░▓▒▒████▒▒██ 
# ─────────█▒▒▒▒██▒▒▒▒▒▒▒▒▒▒▒█▒█░▒████ 
# ─────███████████▒▒▒▒▒▒▒▒██████▒██▓▒███ 
# ─────██▒▒▒▒▒▒█████▒▒▒▒▒▒▒▒█████▒▒▒▒▒██ 
# ───────██▒▒▒▒▒▒▒▓██████▒▒▒▒▒██▒▒▒▒▒▒███ 
# ────█████▒▒▒▒▒▒▒▒▒▒████▒▒▒██▒▒▒▒▒▒███ 
# ────██▒▒▒███▒▒▒▒▒▒▒▒▒▒▓█████▒▒▒▒▒███ 
# ────███▒▒▒▒███▒▒▒▒▒▒▒▒▒▒▒███▓▒▒███ 
# ──────█████▒▒████▒▒▒▒▒▒▒▒▒▒█████ 
# ─────────████▒▒██████▒▒▒▒█████ 
# ────────────███▒▒██████████ 
# ──────────────████▓──█▓█ 
# ────────────────────████ 
# ────────────────────█░█─────█████████ 
# ────────────────────█▓█───█████████████ 
# ──░█████████───────████──██▓███▒▓████ 
# ─█████████████─────█░███████░██████ 
# ───████░▒███▒██────█▓██████████ 
# ─────█████▓▒█████─████ 
# ─────────██████████▓█ 
# ──────────────────█▓█────████▒█▓▒█ 
# ─────────────────█▓██──█████████████ 
# ─────────────────█▓█──██▒████░█████ 
# ────────────────██████████▒██████ 
# ────────────────█▓███████████ 
# ───────────────████ 
# ───────────────█▒█ 
# ───────────────███

Ou, ainda, pode fazer isso escolhendo "Markdown" em determinada célula, como estou fazendo agora, e escrever como se fosse, sei lá, o Word. Para isso, basta ir ao topo no Jupyter Notebook e, onde está "Code", mudar para "Markdown".

Eu faço documentação da seguinte forma:

![Documenta](https://raw.githubusercontent.com/rodolfo-viana/gabsemjupyter/master/img/6328067979739136.png "Documenta")

Você pode escolher seu jeito de documentar... Mas documente a porra toda!

Recado dado, é hora de sujar as mãos e ver como podemos ler dados...

In [2]:
# Vamos carregar as bibliotecas...

import pandas as pd   # Damos o apelido de 'pd' para não ter de repetir 'pandas' 
import numpy as np    # Damos o apelido de 'np' para não ter de repetir 'numpy'

Depois de carregar as bibliotecas, pedimos ao Pandas para ler o arquivo de dados. Nesta análise, escolhi o arquivo `despesas.csv`.

Trata-se do __arquivo de gastos feitos por meio da verba de gabinete dos deputados estaduais__. Eu obtive este `.csv` a partir de um script de raspagem que criei -- ele não está disponível neste formato na internet.

Você pode fazer o download aqui: https://github.com/rodolfo-viana/gabsemjupyter/blob/master/data/despesas.csv.

Para subir os dados do arquivo na memória, Pandas tem um comando bem simples:

    pd.read_csv()

A documentação completa desta função está [aqui](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html), mas você não precisa saber tudo de cabeça. O importante agora é entender o funcionamento -- e como corrigir possíveis erros.

O `pd.read_csv()` lê um arquivo e converte em `DataFrame`. Por exemplo:

    pd.read_csv('despesas.csv')

Mas se eu digitar isso, terei um erro:

In [3]:
dataset = pd.read_csv('despesas.csv')

FileNotFoundError: File b'despesas.csv' does not exist

O primeiro erro que encontramos foi este:

    FileNotFoundError: File b'despesas.csv' does not exist

Motivo: o arquivo não está no mesmo diretório deste notebook. Ele está na pasta `data`.

O correto, portanto, é indicar onde está o arquivo:

    pd.read_csv('data/despesas.csv')

Mas, se eu digitar isso, terei erro novamente -- outro erro.

In [4]:
dataset = pd.read_csv('data/despesas.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 4: invalid start byte

Repare que o tipo de erro mudou: em vez de não encontrar o arquivo, o notebook não conseguiu lê-lo devido a um erro de codificação.

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 4: invalid start byte

Como padrão, Pandas tenta a leitura usando a codificação `utf-8`. Mas nosso arquivo está com outra codificação. Repare no que acontece quando eu o abro num editor de planilhas:

![Encoding](https://raw.githubusercontent.com/rodolfo-viana/gabsemjupyter/master/img/6613531705999360.png "Encoding")

Vê as interrogações nos losangos no meio das palavras? Isso indica que nosso arquivo não está em UTF-8.

Para o Pandas poder ler, é preciso indicar a codificação correta. Isso é feita com `encoding`:

    pd.read_csv('data/despesas.csv', encoding = 'latin-1')

Latin-1 é o apelido do ISO-8859-1. E o que isso quer dizer? Em uma frase captada no [Stack Overflow](https://stackoverflow.com/questions/2708958/differences-between-utf8-and-latin1):

    "UTF-8 is prepared for world domination, Latin-1 isn't."

Para explicar de maneira resumida, UTF-8 contém uma variedade maior de caracteres, enquanto Latin-1 é adequada apenas para línguas derivadas do latim -- e no latim em si não havia cedilha, por exemplo. Daí vem o erro. (E por isso o Pandas vem "de fábrica" preparado para ler UTF-8.)

Vamos testar o comando com o `encoding` definido:

In [5]:
dataset = pd.read_csv('data/despesas.csv', encoding = 'latin-1')

c:\users\rodolfoviana\appdata\python\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Agora funcionou -- mas com um aviso:

    DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.

É um erro de tipo. Nosso dataset tem `string`, `integer` e `float`, e o trabalho de armazenar na memória essa variedade toda precisa ser maior. Por isso, há dois caminhos:

    1. Definir os tipos de cada coluna, ou
    2. Pedir para usar mais memória (ou seja, 'low_memory = False').

Vamos da segunda opção, e depois faremos a primeira:

In [6]:
dataset = pd.read_csv('data/despesas.csv', encoding = 'latin-1', low_memory = False)

Pronto! Nenhum erro!

Vamos testar:

In [7]:
dataset

,Deputado,Matricula,Ano,Mes,Tipo,CNPJ,Fornecedor,Valor
0,ABELARDO CAMARINHA,300257,2015,3,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,200.00
1,ABELARDO CAMARINHA,300257,2015,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,68064740000125,PAPER FACE COMERCIAL LTDA,295.40
2,ABELARDO CAMARINHA,300257,2015,3,N - MORADIA,22145388877,LARA SERVINO VARGAS ABREU,2850.00
3,ABELARDO CAMARINHA,300257,2015,4,A - COMBUSTÍVEIS E LUBRIFICANTES,10915883000113,CENTRO AUTOMOTIVO TOP 23 LTDA,100.00
4,ABELARDO CAMARINHA,300257,2015,4,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,195.01
5,ABELARDO CAMARINHA,300257,2015,4,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06222505000187,WAGNER HUBERT EPP,200.00
6,ABELARDO CAMARINHA,300257,2015,4,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,10455524000120,ROGÉRIO GODOY CARIMBOS - ME,60.00
7,ABELARDO CAMARINHA,300257,2015,4,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",04206050000180,TIM CELULAR SA,719.02
8,ABELARDO CAMARINHA,300257,2015,4,J - SERVIÇOS DE COMUNICAÇÃO,14691478000110,AGENCIA DE SERV POSTAIS AVARÉ LTDA,719.94
9,ABELARDO CAMARINHA,300257,2015,4,N - MORADIA,22145388877,LARA SERVINO VARGAS ABREU,2850.00
10,ABELARDO CAMARINHA,300257,2015,5,A - COMBUSTÍVEIS E LUBRIFICANTES,07846559000186,AUTO POSTO DUQUE DUMONT VILLARES LTDA-ME,205.00
11,ABELARDO CAMARINHA,300257,2015,5,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,170.03
12,ABELARDO CAMARINHA,300257,2015,5,"D - MATERIAIS E SERVIÇOS GRÁFICOS, DE CÓPIAS ...",00338391000159,NINO ARTES GRÁFICAS DE MARÍLIA LTDA EPP,7915.00
13,ABELARDO CAMARINHA,300257,2015,5,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06085866000129,MA DISTRIBUIDORA DE BEBIDAS E PRODUTOS DE HIGI...,225.00
14,ABELARDO CAMARINHA,300257,2015,5,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06222505000187,WAGNER HUBERT EPP,6000.00
15,ABELARDO CAMARINHA,300257,2015,5,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",02558157000162,TELEFONICA BRASIL SA,300.18
16,ABELARDO CAMARINHA,300257,2015,5,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",04206050000180,TIM CELULAR SA,923.27
17,ABELARDO CAMARINHA,300257,2015,6,A - COMBUSTÍVEIS E LUBRIFICANTES,07846559000186,AUTO POSTO DUQUE DUMONT VILLARES LTDA-ME,200.00
18,ABELARDO CAMARINHA,300257,2015,6,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,195.08
19,ABELARDO CAMARINHA,300257,2015,6,"D - MATERIAIS E SERVIÇOS GRÁFICOS, DE CÓPIAS ...",04988313000150,EDITORA CONEXÃO DE MARÍLIA LTDA - ME,7500.00
20,ABELARDO CAMARINHA,300257,2015,6,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06222505000187,WAGNER HUBERT EPP,4800.00
21,ABELARDO CAMARINHA,300257,2015,6,J - SERVIÇOS DE COMUNICAÇÃO,14193306000116,MARIA LUCIA DE OLIVEIRA PEREIRA DOS SANTOS,2700.00
22,ABELARDO CAMARINHA,300257,2015,6,N - MORADIA,22145388877,LARA SERVINO VARGAS ABREU,2850.00
23,ABELARDO CAMARINHA,300257,2015,7,A - COMBUSTÍVEIS E LUBRIFICANTES,07546511000152,AUTO POSTO MONTECARLO DE MARÍLIA LTDA,964.41
24,ABELARDO CAMARINHA,300257,2015,7,"D - MATERIAIS E SERVIÇOS GRÁFICOS, DE CÓPIAS ...",03136828000160,MARCO ANTONIO D AVILA,7500.00
25,ABELARDO CAMARINHA,300257,2015,7,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06222505000187,WAGNER HUBERT EPP,4800.00
26,ABELARDO CAMARINHA,300257,2015,7,"G - ASSINATURAS DE PERIÓDICOS, PUBLICAÇÕES E I...",40432544000147,CLARO SA,172.90
27,ABELARDO CAMARINHA,300257,2015,7,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",33050196000188,CPFL ENERGIA,166.39
28,ABELARDO CAMARINHA,300257,2015,7,J - SERVIÇOS DE COMUNICAÇÃO,14193306000116,MARIA LUCIA DE OLIVEIRA PEREIRA DOS SANTOS,7500.00
29,ABELARDO CAMARINHA,300257,2015,7,N - MORADIA,22145388877,LARA SERVINO VARGAS ABREU,2850.00
...,...,...,...,...,...,...,...,...
446378,ÍTALO CARDOSO,300441,2007,2,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",02558157000162,TELECOMUNICAÇÕES DE SÃO PAULO S.A,95.38
446379,ÍTALO CARDOSO,300441,2007,2,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",33530486000129,EMBRATEL EMPRESA BRASILEIRA DE TELECOMUNICAÇÕES,28.87
446380,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",02740556000140,COMERCIAL ORIENTAL FOOD CENTER LTDA,65.18
446381,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",06878968000100,PATRU PARK,5.00
446382,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",43517978000138,ESTACIONAMENTO PLANALTO S/C LTDA,8.00
446383,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",62925474000282,ASSOCIAÇÃO FUNC.ASSEMB.LEG. EST.SÃO PAULO,61.16
446384,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",66747577000170,IBIZA EUROPEIA ALIMENTOS LTDA,33.76
446385,ÍTALO CARDOSO,300441,2007,2,J - SERVIÇOS DE COMUNICAÇÃO,07047000000196,ECT-EMP.BRAS.CORREIOS E TELEGRAFOS,3499.10
446386,ÍTALO CARDOSO,300441,2007,2,J - SERVIÇOS DE COMUNICAÇÃO,34028316106106,ECT-EMP.BRAS.CORREIOS E TELEGRAFOS,27.40
446387,ÍTALO CARDOSO,300441,2007,3,A - COMBUSTÍVEIS E LUBRIFICANTES,02983939000149,VIAMARECHAL POSTO DE SERVIÇOS LTDA.,39.99
446388,ÍTALO CARDOSO,300441,2007,3,A - COMBUSTÍVEIS E LUBRIFICANTES,60458486000138,AUTO POSTO JARDIM PAULISTA E SERVIÇOS LTDA.,1745.33
446389,ÍTALO CARDOSO,300441,2007,3,A - COMBUSTÍVEIS E LUBRIFICANTES,62630280000179,AUTO POSTO SABARA LTDA.,1891.00
446390,ÍTALO CARDOSO,300441,2007,3,"B - LOCAÇÃO E MANUT DE BENS MÓVEIS E IMÓVEIS, ...",53977740000149,IRATEL INSTALAÇÕES E COMERCIO DE SISTEMAS TELE...,86.00
446391,ÍTALO CARDOSO,300441,2007,3,"B - LOCAÇÃO E MANUT DE BENS MÓVEIS E IMÓVEIS, ...",62268859000133,TRISOFT SISTEMAS LTDA.,1213.33
446392,ÍTALO CARDOSO,300441,2007,3,C - MATERIAIS E SERVIÇOS DE MANUT E CONSERV DE...,07052735000108,WASHINGTON DA SILVA MARIANO MECANICA - ME,892.00
446393,ÍTALO CARDOSO,300441,2007,3,C - MATERIAIS E SERVIÇOS DE MANUT E CONSERV DE...,NaN,PEDÁGIO,12.70
446394,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,00000998000124,HIPE COMERCIO DE PAPEIS LTDA.,2022.30
446395,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,00986363000148,COME'X COMERCIO E REPRESENTAÇÃO LTDA.,500.00
446396,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,03476811002103,DIA BRASIL SOCIEDADE LTDA,14.85
446397,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,43283811003841,KALUNGA COM. E IND.GRÁFICA LTDA.,24.30
446398,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,47508411090988,CIA. BRASILEIRA DE DISTRIBUIÇÃO,46.19
446399,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,61072898000106,EMPRESA DE AGUAS PETROPOLIS PAULISTA LTDA.,24.77
446400,ÍTALO CARDOSO,300441,2007,3,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",02449992005638,VIVO S/A,234.93
446401,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",02740556000140,COMERCIAL ORIENTAL FOOD CENTER LTDA,64.64
446402,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",05591224000139,IBIZA PARK ESTACIONAMENTO LTDA.-ME,6.00
446403,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",06306675000140,OPTEI EXPRESS LTDA.,120.00
446404,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",52204617000122,CHURRASCARIA JANDA LTDA.,2096.80
446405,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",62925474000282,ASSOCIAÇÃO FUNC.ASSEMB.LEG. EST.SÃO PAULO,13.48
446406,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",66747577000170,IBIZA EUROPEIA ALIMENTOS LTDA,38.08
446407,ÍTALO CARDOSO,300441,2007,3,J - SERVIÇOS DE COMUNICAÇÃO,07047000000196,ECT-EMP.BRAS.CORREIOS E TELEGRAFOS,2994.00

Caso você preferisse indicar o tipo das colunas, poderia usar Numpy, e o código ficaria assim:

In [8]:
dataset = pd.read_csv('data/despesas.csv',           # Fui para a linha de baixo para dar leitura
                      encoding = 'latin-1',            
                      dtype = {'Deputado': np.str,
                               'Matricula': np.int,
                               'Ano': np.int,
                               'Mes': np.int,
                               'Tipo': np.str,
                               'CNPJ': np.str,       # Como não vou fazer soma, trato CNPJ como 'str'
                               'Fornecedor': np.str,
                               'Valor': np.float})

Mesmo sem `memory_low = False`, nenhum erro.

Agora que já temos o dataset na memória -- com o nome `dataset` --, vamos ver os dados.

In [9]:
dataset

,Deputado,Matricula,Ano,Mes,Tipo,CNPJ,Fornecedor,Valor
0,ABELARDO CAMARINHA,300257,2015,3,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,200.00
1,ABELARDO CAMARINHA,300257,2015,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,68064740000125,PAPER FACE COMERCIAL LTDA,295.40
2,ABELARDO CAMARINHA,300257,2015,3,N - MORADIA,22145388877,LARA SERVINO VARGAS ABREU,2850.00
3,ABELARDO CAMARINHA,300257,2015,4,A - COMBUSTÍVEIS E LUBRIFICANTES,10915883000113,CENTRO AUTOMOTIVO TOP 23 LTDA,100.00
4,ABELARDO CAMARINHA,300257,2015,4,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,195.01
5,ABELARDO CAMARINHA,300257,2015,4,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06222505000187,WAGNER HUBERT EPP,200.00
6,ABELARDO CAMARINHA,300257,2015,4,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,10455524000120,ROGÉRIO GODOY CARIMBOS - ME,60.00
7,ABELARDO CAMARINHA,300257,2015,4,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",04206050000180,TIM CELULAR SA,719.02
8,ABELARDO CAMARINHA,300257,2015,4,J - SERVIÇOS DE COMUNICAÇÃO,14691478000110,AGENCIA DE SERV POSTAIS AVARÉ LTDA,719.94
9,ABELARDO CAMARINHA,300257,2015,4,N - MORADIA,22145388877,LARA SERVINO VARGAS ABREU,2850.00
10,ABELARDO CAMARINHA,300257,2015,5,A - COMBUSTÍVEIS E LUBRIFICANTES,07846559000186,AUTO POSTO DUQUE DUMONT VILLARES LTDA-ME,205.00
11,ABELARDO CAMARINHA,300257,2015,5,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,170.03
12,ABELARDO CAMARINHA,300257,2015,5,"D - MATERIAIS E SERVIÇOS GRÁFICOS, DE CÓPIAS ...",00338391000159,NINO ARTES GRÁFICAS DE MARÍLIA LTDA EPP,7915.00
13,ABELARDO CAMARINHA,300257,2015,5,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06085866000129,MA DISTRIBUIDORA DE BEBIDAS E PRODUTOS DE HIGI...,225.00
14,ABELARDO CAMARINHA,300257,2015,5,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06222505000187,WAGNER HUBERT EPP,6000.00
15,ABELARDO CAMARINHA,300257,2015,5,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",02558157000162,TELEFONICA BRASIL SA,300.18
16,ABELARDO CAMARINHA,300257,2015,5,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",04206050000180,TIM CELULAR SA,923.27
17,ABELARDO CAMARINHA,300257,2015,6,A - COMBUSTÍVEIS E LUBRIFICANTES,07846559000186,AUTO POSTO DUQUE DUMONT VILLARES LTDA-ME,200.00
18,ABELARDO CAMARINHA,300257,2015,6,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,195.08
19,ABELARDO CAMARINHA,300257,2015,6,"D - MATERIAIS E SERVIÇOS GRÁFICOS, DE CÓPIAS ...",04988313000150,EDITORA CONEXÃO DE MARÍLIA LTDA - ME,7500.00
20,ABELARDO CAMARINHA,300257,2015,6,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06222505000187,WAGNER HUBERT EPP,4800.00
21,ABELARDO CAMARINHA,300257,2015,6,J - SERVIÇOS DE COMUNICAÇÃO,14193306000116,MARIA LUCIA DE OLIVEIRA PEREIRA DOS SANTOS,2700.00
22,ABELARDO CAMARINHA,300257,2015,6,N - MORADIA,22145388877,LARA SERVINO VARGAS ABREU,2850.00
23,ABELARDO CAMARINHA,300257,2015,7,A - COMBUSTÍVEIS E LUBRIFICANTES,07546511000152,AUTO POSTO MONTECARLO DE MARÍLIA LTDA,964.41
24,ABELARDO CAMARINHA,300257,2015,7,"D - MATERIAIS E SERVIÇOS GRÁFICOS, DE CÓPIAS ...",03136828000160,MARCO ANTONIO D AVILA,7500.00
25,ABELARDO CAMARINHA,300257,2015,7,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,06222505000187,WAGNER HUBERT EPP,4800.00
26,ABELARDO CAMARINHA,300257,2015,7,"G - ASSINATURAS DE PERIÓDICOS, PUBLICAÇÕES E I...",40432544000147,CLARO SA,172.90
27,ABELARDO CAMARINHA,300257,2015,7,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",33050196000188,CPFL ENERGIA,166.39
28,ABELARDO CAMARINHA,300257,2015,7,J - SERVIÇOS DE COMUNICAÇÃO,14193306000116,MARIA LUCIA DE OLIVEIRA PEREIRA DOS SANTOS,7500.00
29,ABELARDO CAMARINHA,300257,2015,7,N - MORADIA,22145388877,LARA SERVINO VARGAS ABREU,2850.00
...,...,...,...,...,...,...,...,...
446378,ÍTALO CARDOSO,300441,2007,2,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",02558157000162,TELECOMUNICAÇÕES DE SÃO PAULO S.A,95.38
446379,ÍTALO CARDOSO,300441,2007,2,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",33530486000129,EMBRATEL EMPRESA BRASILEIRA DE TELECOMUNICAÇÕES,28.87
446380,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",02740556000140,COMERCIAL ORIENTAL FOOD CENTER LTDA,65.18
446381,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",06878968000100,PATRU PARK,5.00
446382,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",43517978000138,ESTACIONAMENTO PLANALTO S/C LTDA,8.00
446383,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",62925474000282,ASSOCIAÇÃO FUNC.ASSEMB.LEG. EST.SÃO PAULO,61.16
446384,ÍTALO CARDOSO,300441,2007,2,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",66747577000170,IBIZA EUROPEIA ALIMENTOS LTDA,33.76
446385,ÍTALO CARDOSO,300441,2007,2,J - SERVIÇOS DE COMUNICAÇÃO,07047000000196,ECT-EMP.BRAS.CORREIOS E TELEGRAFOS,3499.10
446386,ÍTALO CARDOSO,300441,2007,2,J - SERVIÇOS DE COMUNICAÇÃO,34028316106106,ECT-EMP.BRAS.CORREIOS E TELEGRAFOS,27.40
446387,ÍTALO CARDOSO,300441,2007,3,A - COMBUSTÍVEIS E LUBRIFICANTES,02983939000149,VIAMARECHAL POSTO DE SERVIÇOS LTDA.,39.99
446388,ÍTALO CARDOSO,300441,2007,3,A - COMBUSTÍVEIS E LUBRIFICANTES,60458486000138,AUTO POSTO JARDIM PAULISTA E SERVIÇOS LTDA.,1745.33
446389,ÍTALO CARDOSO,300441,2007,3,A - COMBUSTÍVEIS E LUBRIFICANTES,62630280000179,AUTO POSTO SABARA LTDA.,1891.00
446390,ÍTALO CARDOSO,300441,2007,3,"B - LOCAÇÃO E MANUT DE BENS MÓVEIS E IMÓVEIS, ...",53977740000149,IRATEL INSTALAÇÕES E COMERCIO DE SISTEMAS TELE...,86.00
446391,ÍTALO CARDOSO,300441,2007,3,"B - LOCAÇÃO E MANUT DE BENS MÓVEIS E IMÓVEIS, ...",62268859000133,TRISOFT SISTEMAS LTDA.,1213.33
446392,ÍTALO CARDOSO,300441,2007,3,C - MATERIAIS E SERVIÇOS DE MANUT E CONSERV DE...,07052735000108,WASHINGTON DA SILVA MARIANO MECANICA - ME,892.00
446393,ÍTALO CARDOSO,300441,2007,3,C - MATERIAIS E SERVIÇOS DE MANUT E CONSERV DE...,NaN,PEDÁGIO,12.70
446394,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,00000998000124,HIPE COMERCIO DE PAPEIS LTDA.,2022.30
446395,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,00986363000148,COME'X COMERCIO E REPRESENTAÇÃO LTDA.,500.00
446396,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,03476811002103,DIA BRASIL SOCIEDADE LTDA,14.85
446397,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,43283811003841,KALUNGA COM. E IND.GRÁFICA LTDA.,24.30
446398,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,47508411090988,CIA. BRASILEIRA DE DISTRIBUIÇÃO,46.19
446399,ÍTALO CARDOSO,300441,2007,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,61072898000106,EMPRESA DE AGUAS PETROPOLIS PAULISTA LTDA.,24.77
446400,ÍTALO CARDOSO,300441,2007,3,"H - SERV.UTIL.PÚBLICA (TELEF.MÓVEL/FIXA, ENERG...",02449992005638,VIVO S/A,234.93
446401,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",02740556000140,COMERCIAL ORIENTAL FOOD CENTER LTDA,64.64
446402,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",05591224000139,IBIZA PARK ESTACIONAMENTO LTDA.-ME,6.00
446403,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",06306675000140,OPTEI EXPRESS LTDA.,120.00
446404,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",52204617000122,CHURRASCARIA JANDA LTDA.,2096.80
446405,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",62925474000282,ASSOCIAÇÃO FUNC.ASSEMB.LEG. EST.SÃO PAULO,13.48
446406,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",66747577000170,IBIZA EUROPEIA ALIMENTOS LTDA,38.08
446407,ÍTALO CARDOSO,300441,2007,3,J - SERVIÇOS DE COMUNICAÇÃO,07047000000196,ECT-EMP.BRAS.CORREIOS E TELEGRAFOS,2994.00

Repare que, além das oito colunas do nosso dataset, o Pandas criou um índice na esquerda -- que começa no 0 (zero). Isso é bastante útil em muitas ocasiões: sabemos, por exemplo, que estamos trabalhando com 446.408 registros (neste caso, notas fiscais).

E por haver tantos registros, o Pandas esconde alguns -- ou teríamos uma lista imensa cuja leitura seria praticamente inútil. Repare que são apresentados os 30 primeiros registros, reticências, e os 30 últimos.

Vamos entrar nos registros logo mais. Por ora, vamos ver o que Pandas pode nos oferecer...

In [10]:
dataset.shape

(446408, 8)

`DataFrame.shape` mostra a dimensão dos registros. Vemos que temos 446.408 linhas (e sabemos que cada uma é uma nota fiscal) e oito colunas.

In [11]:
dataset.dtypes

Deputado       object
Matricula       int32
Ano             int32
Mes             int32
Tipo           object
CNPJ           object
Fornecedor     object
Valor         float64
dtype: object

`DataFrame.dtypes` apresenta o tipo de cada coluna.

In [12]:
dataset.axes

[RangeIndex(start=0, stop=446408, step=1),
 Index(['Deputado', 'Matricula', 'Ano', 'Mes', 'Tipo', 'CNPJ', 'Fornecedor',
        'Valor'],
       dtype='object')]

`DataFrame.axes` mostra os eixos, os nomes de cada coluna.

In [13]:
dataset.head()

,Deputado,Matricula,Ano,Mes,Tipo,CNPJ,Fornecedor,Valor
0,ABELARDO CAMARINHA,300257,2015,3,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,200.00
1,ABELARDO CAMARINHA,300257,2015,3,E - MATERIAIS DE ESCRITÓRIO E OUTROS MATERIAIS...,68064740000125,PAPER FACE COMERCIAL LTDA,295.40
2,ABELARDO CAMARINHA,300257,2015,3,N - MORADIA,22145388877,LARA SERVINO VARGAS ABREU,2850.00
3,ABELARDO CAMARINHA,300257,2015,4,A - COMBUSTÍVEIS E LUBRIFICANTES,10915883000113,CENTRO AUTOMOTIVO TOP 23 LTDA,100.00
4,ABELARDO CAMARINHA,300257,2015,4,A - COMBUSTÍVEIS E LUBRIFICANTES,71806251000106,AUTO POSTO DE SERVIÇOS MARV LTDA,195.01

In [14]:
dataset.tail()

,Deputado,Matricula,Ano,Mes,Tipo,CNPJ,Fornecedor,Valor
446403,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",06306675000140,OPTEI EXPRESS LTDA.,120.00
446404,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",52204617000122,CHURRASCARIA JANDA LTDA.,2096.80
446405,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",62925474000282,ASSOCIAÇÃO FUNC.ASSEMB.LEG. EST.SÃO PAULO,13.48
446406,ÍTALO CARDOSO,300441,2007,3,"I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...",66747577000170,IBIZA EUROPEIA ALIMENTOS LTDA,38.08
446407,ÍTALO CARDOSO,300441,2007,3,J - SERVIÇOS DE COMUNICAÇÃO,07047000000196,ECT-EMP.BRAS.CORREIOS E TELEGRAFOS,2994.00

`DataFrame.head()` mostra os cinco primeiros resultados, enquanto `DataFrame.tail()` mostra os cinco últimos.

São boas funções para você ter uma amostra dos dados sem precisar ver uma lista grande.

Se quiser ver mais que cinco -- digamos, dez --, pode definir assim:

    DataFrame.head(10)
    DataFrame.tail(10)

In [15]:
dataset.iloc[1149]

Deputado                                          ADILSON ROSSI
Matricula                                                300432
Ano                                                        2003
Mes                                                           6
Tipo          I - HOSPEDAGEM, ALIMENTAÇÃO E DESPESAS DE LOCO...
CNPJ                                             56444326000162
Fornecedor                               CLUB 1001 LANCHES LTDA
Valor                                                        66
Name: 1149, dtype: object

`DataFrame.iloc[]` mostra um registro a partir do índice -- "iloc" significa "index location". No caso, estamos vendo o 1.150º registro -- lembrando que o índice começa no 0 (zero).

Agora que sabemos como ler o arquivo, vamos passar para a análise em si. Mas no próximo notebook...

Beijos.